import { HomePageConfig } from '@/types/homepage';

export const DEFAULT_HOMEPAGE_CONFIG: HomePageConfig = {
  heroSlides: [
    {
      id: 1,
      title: 'The Grand Bridal & Heritage Showcase',
      subtitle: 'The eternal charm of authentic handloom silk sarees curated by Retail 360°, woven with pure gold zari and generational artistry.',
      image: '/hero-banner-1.jpg',
      ctaText: 'SHOP NOW',
      ctaLink: '/categories/kanjivaram-silk',
    },
    {
      id: 2,
      title: 'Kadwa Brocades & Varanasi Masterweaves',
      subtitle: 'Hand-interlocked floral jaal and antique meenakari motifs handcrafted on generational pit looms.',
      image: '/hero-banner-2.jpg',
      ctaText: 'SHOP NOW',
      ctaLink: '/categories/banarasi-brocade',
    },
    {
      id: 3,
      title: 'Ethereal Pastels & Organza Tissue Silks',
      subtitle: 'Airy silhouettes adorned with delicate gota patti borders and botanical foil zari drapes.',
      image: '/hero-banner-3.jpg',
      ctaText: 'SHOP NOW',
      ctaLink: '/categories/organza-floral',
    },
  ],
  weaveCraft: {
    badge: 'Curated Artisan Collections',
    title: 'Shop by Weave & Craft',
    subtitle: "Timeless regional handlooms crafted across India's celebrated weaving heritage",
    crafts: [
      {
        id: 1,
        title: 'Kanjivaram Silk',
        badge: 'Temple Korvai',
        href: '/categories/kanjivaram-silk',
        image: '/images/products/saree-emerald-peacock.jpg',
      },
      {
        id: 2,
        title: 'Banarasi Brocade',
        badge: 'Kadwa Jaal',
        href: '/categories/banarasi-brocade',
        image: '/hero-banner-2.jpg',
      },
      {
        id: 3,
        title: 'Organza & Tissue',
        badge: 'Ethereal Sheer',
        href: '/categories/organza-floral',
        image: '/images/products/saree-organza-lotus.jpg',
      },
      {
        id: 4,
        title: 'Chanderi & Linen',
        badge: 'Handloom Grace',
        href: '/categories/chanderi-linen',
        image: 'https://images.pexels.com/photos/2220316/pexels-photo-2220316.jpeg?auto=compress&cs=tinysrgb&w=600',
      },
      {
        id: 5,
        title: 'Bandhani & Leheriya',
        badge: 'Festive Tie-Dye',
        href: '/categories/bandhani-leheriya',
        image: '/images/products/saree-bandhani-gharchola.jpg',
      },
      {
        id: 6,
        title: 'Party & Cocktail',
        badge: 'Modern Silks',
        href: '/categories/party-cocktail-wear',
        image: 'https://images.pexels.com/photos/247287/pexels-photo-247287.jpeg?auto=compress&cs=tinysrgb&w=600',
      },
    ],
  },
  newArrivals: {
    sectionTitle: "Today's New Arrivals",
    links: [
      { label: 'View All New Arrivals', href: '/shop' },
      { label: 'Pure Kanchipuram Silks', href: '/categories/kanjivaram-silk' },
      { label: 'Soft Silk Sarees', href: '/shop?search=soft+silk' },
    ],
    curatedCard: {
      title: 'Curated Combos',
      subtitle: 'Heirloom handloom sarees matched with contrast designer blouse pieces.',
      image: 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=800',
      ctaText: 'SHOP NOW',
      ctaLink: '/shop',
    },
  },
  kanchipuram: {
    badge: '✦ SACRED WEAVES OF SOUTH INDIA ✦',
    title: 'Pure Kanchipuram Silks',
    subtitle: 'Handpicked masterweaves from the historic temple town of Kanchipuram',
    lookbookCard: {
      title: 'Bridal Silks',
      subtitle: 'Authentic 3-ply mulberry silks with certified tested silver & gold zari.',
      image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
      link: '/categories/kanjivaram-silk',
    },
  },
  bridalFestive: {
    badge: 'CELEBRITY & ROYAL LOOKBOOK',
    title: 'Bridal & Festive Edit',
    viewAllLink: '/shop?featured=true',
    cards: [
      {
        id: 'rsf-kanji-001',
        title: 'Royal Saree Black Bridal Kanchipuram Silk Saree',
        price: 32500,
        originalPrice: 38000,
        image: 'https://images.pexels.com/photos/1488312/pexels-photo-1488312.jpeg?auto=compress&cs=tinysrgb&w=800',
        link: '/shop',
      },
      {
        id: 'rsf-banar-001',
        title: 'Sindhoor Red Gold Zari Heavy Bridal Silk Saree',
        price: 36000,
        originalPrice: 42000,
        image: 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=800',
        link: '/shop',
      },
      {
        id: 'rsf-kanji-002',
        title: 'Lavanya Lilac Pastel Brocade Kanchipuram Saree',
        price: 28500,
        originalPrice: 33000,
        image: 'https://images.pexels.com/photos/1730877/pexels-photo-1730877.jpeg?auto=compress&cs=tinysrgb&w=800',
        link: '/shop',
      },
      {
        id: 'rsf-organza-001',
        title: 'Suvarna Beige Tissue Handloom Silk Saree',
        price: 29900,
        originalPrice: 35000,
        image: 'https://images.pexels.com/photos/3014856/pexels-photo-3014856.jpeg?auto=compress&cs=tinysrgb&w=800',
        link: '/shop',
      },
    ],
  },
  videoBanner: {
    badge: 'THE ROYAL WEAVE IN MOTION',
    title: 'Generations of Handloom Artistry Captured on Film',
    description:
      'Witness authentic master artisans at the pit loom weaving pure mulberry silk and certified 24K electroplated gold zari. Each heritage saree represents over 200 hours of unhurried generational rhythm.',
    videoUrl:
      'https://upload.wikimedia.org/wikipedia/commons/b/bd/Weaving_Tant_Saree_by_Handloom_-_2_Natun_Phulia_-_Nadia_2016-11-12_1804.webm',
    poster: '/hero-banner-2.jpg',
    cta1Text: 'EXPLORE BRIDAL EDIT',
    cta1Link: '/shop?featured=true',
    cta2Text: 'BOOK LIVE VIDEO DRAPE',
  },
  weddingStories: {
    badge: 'CELEBRATE TRADITIONS',
    title: 'Wedding & Festive Stories',
    subtitle: 'Curating unforgettable memories for brides and families',
    stories: [
      {
        title: 'Muhurtham',
        subtitle: 'Traditional Sacred Silks',
        image: 'https://images.pexels.com/photos/1488312/pexels-photo-1488312.jpeg?auto=compress&cs=tinysrgb&w=600',
        link: '/shop',
      },
      {
        title: 'Haldi & Sangeet',
        subtitle: 'Sunlit Auspicious Drapes',
        image: 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=600',
        link: '/shop',
      },
      {
        title: 'The Bridal Trousseau',
        subtitle: 'Generational Heirlooms',
        image: 'https://images.pexels.com/photos/3321793/pexels-photo-3321793.jpeg?auto=compress&cs=tinysrgb&w=600',
        link: '/shop',
      },
      {
        title: 'Grand Reception',
        subtitle: 'Opulent Kadwa Brocades',
        image: 'https://images.pexels.com/photos/1730877/pexels-photo-1730877.jpeg?auto=compress&cs=tinysrgb&w=600',
        link: '/shop',
      },
      {
        title: 'Pujas & Celebrations',
        subtitle: 'Festive Auspicious Drapes',
        image: 'https://images.pexels.com/photos/1589216/pexels-photo-1589216.jpeg?auto=compress&cs=tinysrgb&w=600',
        link: '/shop',
      },
    ],
  },
  loomStory: {
    badge: 'AUTHENTIC CRAFTSMANSHIP',
    title: 'Silk Swatches | The Weaving Loom Story',
    subtitle: 'Zoom into the intricate craft of our master weavers',
    swatches: [
      {
        title: 'Pure Tested Zari',
        desc: 'Certified gold & silver plate',
        image: 'https://images.pexels.com/photos/1488312/pexels-photo-1488312.jpeg?auto=compress&cs=tinysrgb&w=400',
      },
      {
        title: 'Korvai Weaving',
        desc: 'Hand-interlocked three-shuttle',
        image: 'https://images.pexels.com/photos/1589216/pexels-photo-1589216.jpeg?auto=compress&cs=tinysrgb&w=400',
      },
      {
        title: 'Kadwa Technique',
        desc: 'No loose floating threads',
        image: 'https://images.pexels.com/photos/3321793/pexels-photo-3321793.jpeg?auto=compress&cs=tinysrgb&w=400',
      },
      {
        title: 'Meenakari Inlay',
        desc: 'Colorful enamel silk threads',
        image: 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=400',
      },
      {
        title: 'Mulberry 3-Ply',
        desc: 'Superior tensile strength & sheen',
        image: 'https://images.pexels.com/photos/1730877/pexels-photo-1730877.jpeg?auto=compress&cs=tinysrgb&w=400',
      },
      {
        title: 'Temple Border',
        desc: 'Sacred gopuram architecture',
        image: 'https://images.pexels.com/photos/3014856/pexels-photo-3014856.jpeg?auto=compress&cs=tinysrgb&w=400',
      },
    ],
  },
  readyToShip: {
    badge: 'Dispatches in 24 Hours',
    title: 'Ready to Ship Sarees',
    viewAllLink: '/shop?inStock=true',
  },
  stores: {
    badge: '✦ OUR RETAIL DESTINATIONS ✦',
    title: 'Visit Our Stores',
    subtitle: 'Experience the touch of authentic handlooms across our flagship showrooms',
    stores: [
      {
        id: 'chennai',
        name: 'T. Nagar, Chennai',
        rating: '4.9',
        reviews: '180+ Reviews',
        address: 'Pondy Bazaar, T. Nagar, Chennai, Tamil Nadu 600017',
        phone: '+91 44 2434 5678',
        hours: '10:00 AM - 9:00 PM',
        image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&q=80&w=800',
        mapQuery: 'T. Nagar Chennai Saree Boutique',
      },
      {
        id: 'bengaluru',
        name: 'Jayanagar, Bengaluru',
        rating: '4.9',
        reviews: '240+ Reviews',
        address: '11th Main, 4th Block, Jayanagar, Bengaluru 560011',
        phone: '+91 80 2656 7890',
        hours: '10:00 AM - 9:30 PM',
        image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=800',
        mapQuery: 'Jayanagar Bengaluru Saree Boutique',
      },
      {
        id: 'hyderabad',
        name: 'Banjara Hills, Hyderabad',
        rating: '4.8',
        reviews: '195+ Reviews',
        address: 'Road No. 10, Banjara Hills, Hyderabad, Telangana 500034',
        phone: '+91 40 2335 1234',
        hours: '10:30 AM - 9:00 PM',
        image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&q=80&w=800',
        mapQuery: 'Banjara Hills Hyderabad Saree Boutique',
      },
      {
        id: 'kolkata',
        name: 'Salt Lake, Kolkata',
        rating: '4.9',
        reviews: '210+ Reviews',
        address: 'TechWave Tower, Sector V, Salt Lake, Kolkata 700091',
        phone: '+91 9641145871',
        hours: '10:00 AM - 9:00 PM',
        image: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&q=80&w=800',
        mapQuery: 'Salt Lake Sector V Kolkata Saree Boutique',
      },
      {
        id: 'delhi',
        name: 'Connaught Place, New Delhi',
        rating: '4.8',
        reviews: '170+ Reviews',
        address: 'Block E, Inner Circle, Connaught Place, New Delhi 110001',
        phone: '+91 11 2341 5678',
        hours: '10:30 AM - 8:30 PM',
        image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&q=80&w=800',
        mapQuery: 'Connaught Place New Delhi Saree Boutique',
      },
      {
        id: 'mumbai',
        name: 'Kala Ghoda, Mumbai',
        rating: '4.9',
        reviews: '220+ Reviews',
        address: 'Heritage Mile, Kala Ghoda, Fort, Mumbai 400001',
        phone: '+91 22 2284 9012',
        hours: '10:00 AM - 9:00 PM',
        image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=800',
        mapQuery: 'Kala Ghoda Fort Mumbai Saree Boutique',
      },
    ],
  },
};
